---
  aws_region: "{{ lookup('env','AWS_DEFAULT_REGION') | default('us-west-1') }}"
  aws_vpc_name: "{{ project }}-vpc"
  aws_vpc_cidr_block: "10.0.0.0/16"
  aws_vpc_subnet_cidr_block: "10.0.1.0/24"
  aws_az_1: "{{ aws_region }}a"
  aws_ec2_instance_type: "{{ instance_type | default('t2.nano') }}"
  aws_ec2_instance_count: "{{ instance_count | default(1) }}"
  aws_ec2_image: "ami-2a34e94a"
  aws_ec2_group_rules:
    - { from_port: 22, to_port: 22, proto: tcp, cidr_ip: "205.251.233.176/29" }
    - { from_port: 22, to_port: 22, proto: tcp, cidr_ip: "205.251.233.160/28" }
    - { from_port: 22, to_port: 22, proto: tcp, cidr_ip: "205.251.233.32/28" }
    - { from_port: 22, to_port: 22, proto: tcp, cidr_ip: "205.251.233.48/29" }
    - { from_port: 22, to_port: 22, proto: tcp, cidr_ip: "205.251.234.32/28" }
