---
cf_api_email: 'login_cloudflare@email.com' # REQUIRED
cf_api_key: 'CLOUDFLARE_API_KEY' #REQUIRED
cf_dns_zone: 'mydomain.com' #OPTIONAL if only one domain
cf_dns_host: 'www' #REQUIRED
email_login: 'myemail@gmail.com' #REQUIRED if confirmation email required
email_pass: 'mypassword' #REQUIRED if confirmation email required
