#!/bin/bash
SSH=$(which ssh)
BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EC2_INVENTORY_FILE="$BASE_PATH/.env/ec2-inventory"
if [ ! -r "$EC2_INVENTORY_FILE" ]; then
    echo "The inventory file [$EC2_INVENTORY_FILE] does not exist."
    exit 1
fi
EC2_DNS_NAME="$(head -n 1 "$EC2_INVENTORY_FILE")"
$SSH -o StrictHostKeyChecking=no $EC2_DNS_NAME
