#!/bin/bash
BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $BASE_PATH/bootstrap.sh
AWS_VARS=$(cat config.yaml | grep '^aws' | cut -d '#' -f 1 | sed 's/\([^:]*\)/\U\1/' | tr ':' '=' | tr "'" '"' | tr -d ' ')
SCP=$(which scp)
while read line; do
    eval "export $line"
done <<< "$AWS_VARS"
QUERY_PARAM="Reservations[].Instances[].[PublicDnsName,Tags[?Key=='Name'].Value[],InstanceType,PublicIpAddress]"
FILTER_PARAM="Name=instance-state-name,Values=running"
PYTHON_SCRIPT="import sys, json; j=json.load(sys.stdin); l="\n".join([sys.argv[1].format(x[0],x[1][0],x[2],x[3]) for x in j]); print l"
INSTANCES_DETAILS=$($ENV_PATH/bin/aws ec2 describe-instances --query $QUERY_PARAM --filters $FILTER_PARAM)
INSTANCES_PLAIN_DETAILS="$(echo $INSTANCES_DETAILS | $ENV_PATH/bin/python -c 'import sys, json; j=json.load(sys.stdin); l="\n".join([sys.argv[1].format(x[0],x[1][0],x[2],x[3]) for x in j]); print l' "{}")"
if [ -z "$INSTANCES_PLAIN_DETAILS" ]; then
    echo "No instances. Exiting."
    exit 0
fi
LINE=1
if [[ $1 =~ ^-?[0-9]+$ ]]; then
    LINE=$1
    shift
    if [ -r "$1" ]; then
        FILE="$1"
        shift
    fi
elif [ -r "$1" ]; then
    FILE="$1"
    shift
fi
EC2_DNS_NAME="$(echo "$INSTANCES_PLAIN_DETAILS" | head -n $LINE | tail -n 1)"
echo "Connecting to [$EC2_DNS_NAME]"
$SCP -o StrictHostKeyChecking=no -P 443 "$FILE" $EC2_DNS_NAME:/tmp $@
