#!/bin/bash
BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $BASE_PATH/bootstrap.sh
AWS_VARS=$(cat config.yaml | grep '^aws' | cut -d '#' -f 1 | sed 's/\([^:]*\)/\U\1/' | tr ':' '=' | tr "'" '"' | tr -d ' ')
while read line; do
    eval "export $line"
done <<< "$AWS_VARS"
BASE_ARGS="--region us-west-1 ec2 describe-images --owners 379101102735 --filters \"Name=architecture,Values=x86_64\" \"Name=name,Values=debian-jessie-*\" \"Name=root-device-type,Values=ebs\" \"Name=virtualization-type,Values=hvm\" --output text"
exec $ENV_PATH/bin/aws $BASE_ARGS | grep "jessie" | awk '{print $3 " " $8}'  | sort -k1 | tail -n 1 | cut -d ' ' -f 2

