#!/bin/bash
BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $BASE_PATH/bootstrap.sh

RASPBIAN_PATH="$ENV_PATH/raspbian"
RASPBIAN_EXTRACT_PATH="$RASPBIAN_PATH/extract"
RASPBIAN_FILENAME="raspbian-latest.zip"
RASPBIAN_FILE="$RASPBIAN_PATH/$RASPBIAN_FILENAME"
RASPBIAN_LATEST_URL="http://downloads.raspberrypi.org/raspbian_lite_latest"

ARMBIAN_OPIONE_PATH="$ENV_PATH/one"
ARMBIAN_OPIONE_FILENAME="Debian_jessie_default.7z"
ARMBIAN_OPIONE_FILE="$ARMBIAN_OPIONE_PATH/$ARMBIAN_OPIONE_FILENAME"
ARMBIAN_OPIONE_URL="https://dl.armbian.com/orangepione/$ARMBIAN_OPIONE_FILENAME"

ARMBIAN_OPIZERO_PATH="$ENV_PATH/ozero"
ARMBIAN_OPIZERO_FILENAME="Debian_jessie_default.7z"
ARMBIAN_OPIZERO_FILE="$ARMBIAN_OPIZERO_PATH/$ARMBIAN_OPIZERO_FILENAME"
ARMBIAN_OPIZERO_URL="https://dl.armbian.com/orangepizero/$ARMBIAN_OPIZERO_FILENAME"

CURL="$(which curl)"
UNZIP="$(which 7za)"
DISKUTIL="$(which diskutil)"
SUDO="$(which sudo)"
DD="$(which dd)"
MOUNT="$(which mount)"

if [ "$1" = "one" ]; then
    RASPBIAN_PATH="$ARMBIAN_OPIONE_PATH"
    RASPBIAN_EXTRACT_PATH="$ARMBIAN_OPIONE_PATH/extract"
    RASPBIAN_FILE="$ARMBIAN_OPIONE_FILE"
    RASPBIAN_LATEST_URL="$ARMBIAN_OPIONE_URL"
elif [ "$1" = "ozero" ]; then
    RASPBIAN_PATH="$ARMBIAN_OPIZERO_PATH"
    RASPBIAN_EXTRACT_PATH="$ARMBIAN_OPIZERO_PATH"
    RASPBIAN_FILE="$ARMBIAN_OPIZERO_FILE"
    RASPBIAN_LATEST_URL="$ARMBIAN_OPIZERO_URL"
fi

mkdir -p "$RASPBIAN_EXTRACT_PATH"

if [ ! -r "$RASPBIAN_FILE" ]; then
    echo "Downloading latest image [$RASPBIAN_LATEST_URL]"
    $CURL -L -o "$RASPBIAN_FILE" "$RASPBIAN_LATEST_URL"
fi
RASPBIAN_IMAGEFILE="$(find "$RASPBIAN_EXTRACT_PATH" -name "*.img" | head -n 1)"
if [ ! -r "$RASPBIAN_IMAGEFILE" ]; then
    $UNZIP x -o"$RASPBIAN_EXTRACT_PATH" "$RASPBIAN_FILE"
    RASPBIAN_IMAGEFILE="$(find "$RASPBIAN_EXTRACT_PATH" -name "*.img" | head -n 1)"
fi
for DISKFORMAT in Windows_FAT_32 DOS_FAT_32 Windows_FAT_16 Windows_NTFS Linux; do
    SDCARD_DISKID=$($DISKUTIL list | grep "$DISKFORMAT" | tr ' ' '\n' | grep -e 'disk[0-9]')
    if [ ! -z "$SDCARD_DISKID" ]; then
        break;
    fi
done
if [ -z "$SDCARD_DISKID" ]; then
    echo "Unable to find the SD Card mounted in your system. Exiting."
    exit 1
fi
echo "SD Card in [$SDCARD_DISKID][${SDCARD_DISKID%??}]"
$SUDO $DISKUTIL unmount $SDCARD_DISKID
$SUDO $DD bs=1m if=$RASPBIAN_IMAGEFILE of=/dev/r${SDCARD_DISKID%??}
for DISKFORMAT in Windows_FAT_32 DOS_FAT_32 Windows_FAT_16 Windows_NTFS Linux; do
    SDCARD_DISKID=$($DISKUTIL list | grep "$DISKFORMAT" | tr ' ' '\n' | grep -e 'disk[0-9]')
    if [ ! -z "$SDCARD_DISKID" ]; then
        break;
    fi
done
if [ -z "$SDCARD_DISKID" ]; then
    echo "Unable to find the SD Card mounted in your system. Exiting."
    exit 1
fi
MOUNT_POINT=$($MOUNT | grep "${SDCARD_DISKID%??}" | awk '{print $3}')
touch $MOUNT_POINT/ssh

if [ "$1" = "zero" ]; then
    echo "dtoverlay=dwc2" >> "$MOUNT_POINT/config.txt"
    sed -i -e 's/rootwait/rootwait modules-load=dwc2,g_ether/g' "$MOUNT_POINT/cmdline.txt"
fi
$SUDO $DISKUTIL umount $SDCARD_DISKID
