#!/bin/bash
SSH=$(which ssh)
BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EC2_INVENTORY_FILE="$BASE_PATH/.env/ec2-inventory"
if [ ! -r "$EC2_INVENTORY_FILE" ]; then
    echo "The inventory file [$EC2_INVENTORY_FILE] does not exist."
    exit 1
fi
REMOTE_PORT="80"
if [ -n "$1" -a "${1:-0}" -gt 0 ]; then
    REMOTE_PORT="$1"
fi
LOCAL_PORT="8090"
if [ -n "$2" -a "${2:-0}" -gt 0 ]; then
    LOCAL_PORT="$2"
fi
LSOF="$(which lsof)"
if $LSOF -Pi :$LOCAL_PORT -sTCP:LISTEN -t >/dev/null ; then
    echo "Port $LOCAL_PORT is in use"
    exit 1
fi
EC2_DNS_NAME="$(head -n 1 "$EC2_INVENTORY_FILE")"
echo "Trying to open 127.0.0.1:$LOCAL_PORT [http://127.0.0.1:$LOCAL_PORT] connected to $EC2_DNS_NAME:$REMOTE_PORT"
echo "Use Crtl-C to end"
$SSH -N -L $LOCAL_PORT:127.0.0.1:$REMOTE_PORT -o StrictHostKeyChecking=no $EC2_DNS_NAME
