---
- name: Install required packages
  apt: 
    name: "{{ item }}" 
    state: latest
  with_items: "{{ apt_packages }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
