---
  project: "{{ lookup('env', 'ANSIBLE_EC2_PROJECT_NAME') | default('testone') }}"
  aws_private_key_file: "{{ lookup('env','ENV_PATH') | default('.env') }}/aws-key-{{ project }}-private.pem"
  aws_ssh_user: "admin"
  main_ssh_user: "gonzalo"
  main_private_key_file: "{{ lookup('env','HOME') }}/.ssh/GonzaloAlvarez-MasterSSH-privkey.pem"
  ansible_ssh_private_key_file: "{{ main_private_key_file }}"
  ansible_ssh_user: "{{ main_ssh_user }}"
  raspberry_ssh_user: "pi"
  raspberry_ssh_pass: "raspberry"
