---
- name: Update APT cache
  apt: 
    cache_valid_time: "{{ apt_cache_valid_time }}"
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Install aptitude to upgrade system
  apt: 
    pkg: aptitude 
    state: latest
  when: ( quick | default('false') | match('false') ) and
        ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )  
- name: Upgrade system
  apt: 
    upgrade: safe 
    update_cache: yes
  when: ( quick | default('false') | match('false') ) and
        ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
