---

- name: Include OS specific vars
  include_vars: "{{ item }}.yml"
  with_first_found:
    - "{{ ansible_os_family }}"
    - default
  ignore_errors: true

- include: hardening.yml
  become: True
  become_user: root
  become_method: sudo

