---
- name: Install Required Packages
  apt: pkg="{{ item }}" state=latest
  with_items: "{{ credentials_packages }}"
- name: Create temporary path
  command: mktemp -d
  register: credentials_temp_folder
- name: Bring the credentials repo to temporary path
  git:
    repo: 'https://github.com/GonzaloAlvarez/credentials.git'
    dest: '{{ credentials_temp_folder.stdout }}/credentials'
- name: Copy private GPG key file
  copy:
    src: '{{ gpg_key_file }}'
    dest: '{{ credentials_temp_folder.stdout }}/gpg-privkey.pem'
    mode: 0600
- name: Dump the GPG master passphrase
  copy:
    content: '{{ gpg_key_passphrase }}'
    dest: '{{ credentials_temp_folder.stdout }}/gpg-key-passphrase.pem'
    mode: 0600
- name: Import GPG Key into ring
  shell: gpg --homedir "{{ credentials_temp_folder.stdout }}" --batch -q --import "{{ credentials_temp_folder.stdout }}/gpg-privkey.pem"
- name: Decrypt required files
  shell: cat "{{ credentials_temp_folder.stdout }}/gpg-key-passphrase.pem" | gpg --homedir "{{ credentials_temp_folder.stdout }}" --batch -q --passphrase-fd 0 --output "{{ credentials_temp_folder.stdout }}/credentials/{{ decfile_item.split('.enc')[0] }}" --decrypt "{{ credentials_temp_folder.stdout }}/credentials/{{ decfile_item }}"
  with_items: "{{ decrypt_files }}"
  loop_control:
    loop_var: decfile_item
