---
- name: Purge APT packages
  apt: 
    pkg: "{{ item }}" 
    autoremove: yes
    purge: yes
    state: absent
  with_items: "{{ ubuntu_purge_packages | default([]) }}"
  when: ansible_distribution == 'Ubuntu'
- name: Purge YUM packages
  yum:
    pkg: "{{ item }}"
    state: absent
  with_items: "{{ amazon_purge_packages | default([]) }}"
  when: ansible_distribution == 'RedHat'
