- name: "Create new instance in ec2"
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - ec2
- name: "Execute base configuration"
  hosts: all
  gather_facts: True
  become: True
  become_user: root
  become_method: sudo
  roles:
    - { role: 'base', when: purge | default('false') | match('false') }
