---
- name: "Create new instance in ec2"
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - ec2
- name: "Add minimal user configurations"
  hosts: "tag_Project_{{ lookup('env', 'ANSIBLE_EC2_PROJECT_NAME') | default('testone') }}"
  vars:
    ansible_ssh_private_key_file: "{{ aws_private_key_file }}"
    ansible_ssh_user: "{{ aws_ssh_user }}"
  gather_facts: False
  become: True
  become_user: root
  become_method: sudo
  pre_tasks:
    - name: Wait for host to be up
      local_action:
        wait_for
        host={{ inventory_hostname }}
        port=22
        delay=5
        timeout=300
      become: False
    - name: "Update apt-get cache to install python if on Ubuntu"
      raw: sudo apt-get update
      when: ansible_ssh_user == 'ubuntu'
    - name: "Ensure python is installed in Ubuntu systems"
      raw: sudo apt-get -y install python-simplejson
      when: ansible_ssh_user == 'ubuntu'
  roles:
    - role: 'users'
- name: "Execute roles"
  hosts: "tag_Project_{{ lookup('env', 'ANSIBLE_EC2_PROJECT_NAME') | default('testone') }}"
  gather_facts: True
  roles:
    - role: 'ssh-hardening'
    - role: 'base'
    - role: 'sslh'
    - role: 'msmtp'
    - role: 'keyboard'
