- name: "Add minimal user configurations"
  hosts: all
  vars:
    ansible_ssh_user: "pi"
    ansible_ssh_pass: "raspberry"
  gather_facts: False
  become: True
  become_user: root
  become_method: sudo
  roles:
    - { role: 'users', when: purge | default('false') | match('false') }
- name: "Execute base configuration"
  hosts: all
  gather_facts: True
  roles:
    - { role: 'base', when: purge | default('false') | match('false') }
