- name: "Add minimal user configurations"
  hosts: all
  vars:
    ansible_ssh_user: "{{ raspberry_ssh_user }}"
    ansible_ssh_pass: "{{ raspberry_ssh_pass }}"
  gather_facts: False
  become: True
  become_user: root
  become_method: sudo
  roles:
    - role: 'users'
- name: "Execute base configuration"
  hosts: all
  gather_facts: True
  include_vars:
    - rpi-defaults.yml
  roles:
    - role: 'base'
    - role: 'rpi'
