---
  - name: Get Linux Kernel sources
    get_url:
      url: "https://cdn.kernel.org/pub/linux/kernel/v{{ kernel_branch_version}}/linux-{{ kernel_version }}.tar.gz"
      dest: "{{ ansible_env.HOME }}/linux-kernel-source.tar.gz"
    register: kernel_fetch
  - name: unpack the kernel source
    unarchive:
      src: "{{ ansible_env.HOME }}/linux-kernel-source.tar.gz"
      dest: "{{ ansible_env.HOME }}"
      remote_src: yes
    when: kernel_fetch|changed
  - name: remove kernel tar file
    file:
      name: "{{ ansible_env.HOME }}/linux-kernel-source.tar.gz"
      state: absent 
