---
- name: Gathering facts about the instances
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters: 
      "tag:Name": "{{ project }}-{{ aws_region }}-instance"
      instance-state-name: running
  register: ec2_instance_facts
- name: Remove cloudwatch alarms
  ec2_metric_alarm:
    name: "cpu-low-{{ instance_item.id }}"
    region: "{{ aws_region }}"
    state: absent
  with_items: "{{ ec2_instance_facts.instances }}"
  when: ec2_instance_facts.instances|length > 0
  loop_control:
    loop_var: instance_item

