---
- name: Create a new EIP inside the VPC
  ec2_eip: 
    region: "{{ aws_region }}"
    device_id: "{{ instance_item.id }}"
    in_vpc: yes
    reuse_existing_ip_allowed: yes
    state: present
  with_items: "{{ ec2_instances }}"
  when: ( ec2_instances_changed ) and ( ec2_instances|length > 0 )
  loop_control:
    loop_var: instance_item
  register: ec2_eip_facts
- name: Refresh inventory
  meta: refresh_inventory
