---
- name: Create the AWS instance
  ec2:
    key_name: "{{ project }}-aws-key"
    instance_type: "{{ aws_ec2_instance_type }}"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ aws_vpc_subnet.subnet.id }}"
    group: "{{ project }}-secgroup"
    exact_count: "{{ aws_ec2_instance_count }}"
    assign_public_ip: yes
    wait: yes
    image: "{{ aws_ec2_image }}"
    instance_tags:
      Name: "{{ project }}-{{ aws_region }}-instance"
    count_tag:
      Name: "{{ project }}-{{ aws_region }}-instance"
  register: aws_ec2_facts
- name: Set instances created as a fact
  set_fact:
    ec2_instances: "{{ aws_ec2_facts.instances }}"
    ec2_instances_changed: "{{ aws_ec2_facts.changed }}"
