---
- name: Create the AWS instances
  ec2:
    key_name: "{{ project }}-aws-key"
    instance_type: "{{ aws_ec2_instance_type }}"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ aws_vpc_subnet.subnet.id }}"
    group: "{{ project }}-secgroup"
    exact_count: "{{ instance_item.0.count }}"
    volumes:
      - device_name: "{{ aws_ec2_main_volume_prefix | default('/dev/') }}{{ aws_ec2_main_volume | default('xvda') }}"
        volume_type: gp2
        volume_size: "{{ aws_ec2_main_volume_size | default(25) }}"
        delete_on_termination: true
    assign_public_ip: yes
    wait: yes
    image: "{{ aws_ec2_image }}"
    instance_tags: "{{ instance_item.1 }}"
    count_tag: "{{ instance_item.1 }}"
  with_subelements:
    - "{{ aws_ec2_instances }}"
    - tags
  loop_control:
    loop_var: instance_item
- name: Gathering facts about the instances
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters: 
      "tag:Name": "{{ project }}-{{ aws_region }}-instance"
      instance-state-name: running
  register: aws_ec2_facts
- name: Set instances created as a fact
  set_fact:
    ec2_instances: "{{ aws_ec2_facts.instances }}"
    ec2_instances_changed: "{{ aws_ec2_facts.changed }}"
