---
- name: Create a new ec2 key pair 
  ec2_key:
    state: present
    region: "{{ aws_region }}"
    name: "{{ project }}-aws-key"
  register: ec2_key
- name: Save Private Key
  copy: content="{{ ec2_key.key.private_key }}" dest="{{ ec2_key_path }}" mode=0600
  when: ec2_key.changed
