---
- name: Gather facts about the VPC
  ec2_vpc_net_facts:
    region: "{{ aws_region }}"
    filters: { "tag:Name":"{{ aws_vpc_name }}" }
  register: aws_vpc_facts
- name: Remove Security Group
  ec2_group:
    state: absent
    region: "{{ aws_region }}"
    name: "{{ project }}-secgroup"
    vpc_id: "{{ vpc_item.id }}"
    description: "{{ project }} Security Group"
  with_items: "{{ aws_vpc_facts.vpcs }}"
  when: aws_vpc_facts.vpcs|length > 0
  loop_control:
    loop_var: vpc_item

