---
- name: Gathering facts about the instances
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters: 
      "tag:Name": "{{ project }}-{{ aws_region }}-instance"
      instance-state-name: running
  register: ec2_instance_facts
- name: Wait for SSH to come up
  wait_for:
    host={{ instance_item.public_dns_name }}
    port=22
    delay=60
    timeout=320
    state=started
    search_regex=OpenSSH
  with_items: "{{ ec2_instance_facts.instances }}"
  when: ec2_instance_facts.instances|length > 0
  loop_control:
    loop_var: instance_item

