---
- name: Install required packages
  apt: 
    name: "{{ item }}" 
    state: latest
  with_items: "{{ apt_packages | default([]) }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Install required packages
  yum: 
    name: "{{ item }}" 
    state: latest
  with_items: "{{ yum_packages | default([]) }}"
  when: ansible_distribution == 'RedHat'
