---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"

- include: "{{ task_item }}.yml"
  become: True
  become_user: root
  become_method: sudo
  with_items: "{{ root_tasks | default([]) }}"
  loop_control:
    loop_var: task_item
