---
- name: Update CloudFlare DNS servers
  cloudflare_dns:
    zone: "{{ cfdns_zone }}"
    record: "{{ cfdns_record }}"
    type: A
    solo: true
    value: "{{ cfdns_targetip | default(inventory_hostname)}}"
    account_email: "{{ cfdns_login_email }}"
    account_api_token: "{{ cfdns_login_apitoken }}"
  when: play_hosts.index(inventory_hostname) == 0
