---
- name: Send mail notification
  shell: echo "System [{{ inventory_hostname }}] up and running. \n\nVMSTAT:\n$(vmstat)\n\nNETSTAT:\n$(netstat -lntp)\n\nUPTIME:\n$(uptime)" | mail -s "System [{{ inventory_hostname }}] up and running" {{ msmtp_default_recipient }} 
