---
- name: Send mail notification
  shell: echo "System [{{ inventory_hostname }}] up and running on {{lookup('pipe','date +%Y%m%d%H%M%S')}}.\n\nThank you!" | mail -s "System [{{ inventory_hostname }}] up and running" {{ msmtp_default_recipient }} 
