---
dependencies:
  - { role: python3 }
  - { role: acl }
  - { role: letsencrypt-cf }
  - role: nginx
    nginx_configs:
      connection_upgrade:
        - |
          map $http_upgrade $connection_upgrade {
              default upgrade;
              ''      close;
          }
    nginx_sites:
      homeassistant:
        - |
          listen 8443 ssl;
          server_name "{{ lookup('env', 'CF_DNS_HOST') | default('server') }}.{{ lookup('env', 'CF_DNS_ZONE') | default('gon.al') }}";
          location / {
              proxy_pass http://localhost:{{ hass_server_port }};
              proxy_set_header Host $host;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
          }
          ssl_certificate "{{ ssl_fullchaincert_file }}";
          ssl_certificate_key "{{ ssl_privatekey_file }}";
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
          ssl_dhparam "{{ ssl_dhparam_file }}";
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
          proxy_buffering off;
