---
- name: Configure options in /boot/config.txt.
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ rpi_item.regexp }}"
    line: "{{ rpi_item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ raspberry_pi_boot_config_options }}"
  loop_control:
    loop_var: rpi_item

- name: Configure options in /etc/rc.local.
  lineinfile:
    dest: /etc/rc.local
    regexp: "{{ rpi_item.regexp }}"
    line: "{{ rpi_item.line }}"
    insertbefore: "^exit"
    state: present
  with_items: "{{ raspberry_pi_rc_local_options }}"
  loop_control:
    loop_var: rpi_item

- name: Apply configuration
  command: raspi-config --apply-os-config
