---
- name: Disable swap
  shell: dphys-swapfile swapoff
  ignore_errors: True
- name: Remove swap
  shell: dphys-swapfile uninstall
  ignore_errors: True
- name: Uninstall swap program
  apt:
    name: dphys-swapfile
    state: absent
    autoremove: true
    purge: true
